/**
 * Shared MCP prompt registrations.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

export function registerPrompts(server: McpServer): void {
  // Prompt 1: Grid Briefing
  server.registerPrompt("grid_briefing", {
    title: "Grid Briefing",
    description: "Comprehensive California grid briefing — chains all tools automatically.",
  }, async () => ({
    messages: [{
      role: "user" as const,
      content: {
        type: "text" as const,
        text: [
          "Give me a current briefing on the California electricity grid.",
          "",
          "Please:",
          "1. First get the current market snapshot to see prices, load, and generation mix",
          "2. Then check if the current price is unusual compared to historical patterns",
          "3. If anything looks noteworthy, explain what's driving those conditions",
          "",
          "Present your findings as a concise analyst briefing.",
        ].join("\n"),
      },
    }],
  }));

  // Prompt 2: Investigate Price
  server.registerPrompt("investigate_price", {
    title: "Investigate Price",
    description: "Structured price investigation for a specific ISO.",
    argsSchema: {
      iso: z.string().default("CAISO").describe("ISO to investigate (e.g., CAISO)"),
    },
  }, async ({ iso }) => ({
    messages: [{
      role: "user" as const,
      content: {
        type: "text" as const,
        text: [
          `I want to understand what's happening with electricity prices on the ${iso} grid right now.`,
          "",
          "Please follow this investigation flow:",
          "1. Check if the current price is unusual (use is_price_unusual)",
          "2. If the price IS unusual (sigma > 2), get an AI explanation of what's driving it (use explain_grid_conditions with focus on 'prices')",
          "3. If the price is NOT unusual, just get the market snapshot and summarize conditions",
          "",
          "Walk me through your findings step by step.",
        ].join("\n"),
      },
    }],
  }));

  // Prompt 3: Tutorial
  server.registerPrompt("tutorial", {
    title: "GridStatus Tutorial",
    description: "Interactive guided walkthrough of all GridStatus MCP features. Start here if you're new!",
  }, async () => ({
    messages: [{
      role: "user" as const,
      content: {
        type: "text" as const,
        text: [
          "I want to take the GridStatus MCP tutorial. Please guide me through it interactively.",
          "",
          "=== TUTORIAL INSTRUCTIONS FOR CLAUDE ===",
          "",
          "You are running a guided, interactive tutorial for the GridStatus MCP server.",
          "Walk the user through each step below, ONE AT A TIME. After each step, pause",
          "and wait for the user to respond before moving on. If they ask questions along",
          "the way, answer them and then resume where you left off.",
          "Keep your tone friendly and practical — the user is technically comfortable",
          "(they use Claude Desktop and work with energy data) but may be new to MCP.",
          "",
          "STEP 1: WELCOME & ORIENTATION",
          "Welcome the user. This MCP server connects Claude to live electricity grid data —",
          "prices, generation mix, demand, and weather — for the California power grid.",
          "Give them the lay of the land:",
          "- 3 tools for real-time California grid data (each takes a different approach)",
          "- A 4th premium tool unlocked by authentication (historical data across all 7 US power markets)",
          "- 2 resources with background reference info",
          "- 3 prompts including this tutorial",
          "Point out the '+' menu in Claude Desktop — that's where they'll find everything:",
          "- Prompts kick off workflows (like this tutorial)",
          "- Resources are reference material they can pull in for extra context",
          "Tell the user: 'Try clicking the + button to browse what's available. When you're ready, just say Next.'",
          "",
          "STEP 2: MARKET SNAPSHOT — Live Grid Data",
          "Context: 'Let's start with a live snapshot of the California grid.'",
          "Ask: 'Try: What's happening on the California grid?'",
          "Or something specific: 'How much solar is California generating right now?'",
          "Note: The first time a tool runs, Claude Desktop will ask the user to allow it.",
          "Let them know they can click 'Allow for This Chat' or 'Allow Always' — either works.",
          "When they do, call get_market_snapshot. Walk through what they got:",
          "- Prices at three California trading hubs (NP15, SP15, ZP26)",
          "- Current demand in megawatts — how much electricity the state is using right now",
          "- Generation mix — where power is coming from (solar, wind, gas, batteries, etc.)",
          "Then the insight: This data comes straight from CAISO — California's grid operator.",
          "No AI involved. I (Claude) am presenting it conversationally, but the numbers are raw data.",
          "Same query at the same time always gives the same answer.",
          "Then say: 'Next, let's see if that price is normal. Say Next when ready.'",
          "",
          "STEP 3: PRICE ANALYSIS — Is This Normal?",
          "Context: 'You saw the price. But is it high? Low? Normal for this time of day?'",
          "Ask: 'Try: Is that price normal? or How does the current price compare to yesterday?'",
          "When they do, call is_price_unusual. Walk through the key metrics:",
          "- Sigma: standard deviations from the mean for this hour (higher = more unusual)",
          "- Percentile: where this price ranks (95th = higher than 95% of historical readings)",
          "- Severity: a plain-language rating — normal, elevated, high, or extreme",
          "Then the insight: Still no AI — this compares the price against hourly baselines",
          "and a rolling 7-day statistical window. Pure statistics. Same price at the same hour",
          "always gives the same verdict. That consistency is the point.",
          "IMPORTANT: Do NOT speculate about why the price is what it is — that's what Step 4 is for.",
          "Then say: 'We have the what. Now let's find out the why. Say Next when ready.'",
          "",
          "STEP 4: AI EXPLANATION — The 'Why' Behind the Numbers",
          "Context: 'So far we've seen the data and the stats. Now let's find out why",
          "conditions are the way they are.'",
          "Ask: 'Try: Why are prices like this? or What's driving grid conditions right now?'",
          "When they do, call explain_grid_conditions. Walk through what came back:",
          "- It identified specific contributing factors and ranked them by impact",
          "- The explanation connects weather, generation mix, and demand into a coherent story",
          "Then the insight: This tool is different from the first two. It pulled in live weather",
          "data for Sacramento, LA, and San Francisco, combined it with the grid data you already saw,",
          "and fed everything to an AI analyst on the server. Then I (Claude) added a second layer",
          "of interpretation when presenting it to you — two AIs, one answer.",
          "Then say: 'Almost done — one more topic. Say Next when ready.'",
          "",
          "STEP 5: UNLOCK — Authentication & Premium Tools",
          "Context: 'Everything so far used public California data — no account needed. There's more.'",
          "Explain: There's a 4th tool that opens up historical data across all 7 major US",
          "power markets. It requires a gridstatus.io API key.",
          "",
          "Check if query_grid_history is already in your tool list.",
          "- If YES: The user signed in with an API key when they connected. Ask them to try it:",
          "  'What were ERCOT prices last Tuesday?' or 'Show me PJM load data for the past week'",
          "  After showing results, point out: this data comes from the gridstatus.io hosted API —",
          "  a different data source with much broader coverage, authenticated with their key.",
          "- If NO: The user doesn't have an API key configured yet — that's why they have 3 tools",
          "  instead of 4. Let them know they can unlock it:",
          "  1. Get a free API key at gridstatus.io (just an email signup)",
          "  2. Open Claude Desktop Settings → Extensions → GridStatus → add the API key",
          "  3. Restart Claude Desktop — the 4th tool will appear automatically",
          "  'Your key is stored securely by Claude Desktop. And this conversation will still be here",
          "  when you get back.'",
          "  If they want to skip: 'No rush — everything else works without an account. Say Next to continue.'",
          "Either way, share the insight: you started with 3 free tools that work out of the box.",
          "Add a key in the extension settings, restart, and a 4th unlocks automatically.",
          "Then say: 'Say Next when ready for the last step.'",
          "",
          "STEP 6: EXPLORE ON YOUR OWN",
          "Wrap up by showing them what's possible beyond the tutorial:",
          "- The '+' menu has two more prompts: 'Grid Briefing' chains all three tools together",
          "  for a complete picture, and 'Investigate Price' runs a focused price investigation",
          "- Under Resources, 'CAISO Overview' gives background context about the California grid",
          "- Or just ask naturally — 'Give me a full grid analysis' or 'What's driving prices?'",
          "  and Claude will pick the right tools automatically",
          "Quick recap of the tools:",
          "  • Market Snapshot — live conditions, no AI, instant",
          "  • Price Analysis — statistical comparison against baselines, no AI",
          "  • Explain Conditions — AI-powered analysis connecting weather + grid data",
          "  • Historical Grid Data — query any US ISO's history (requires API key)",
          "End with: 'That's the tour! You've seen everything this server can do. Have fun exploring the grid.'",
        ].join("\n"),
      },
    }],
  }));
}
